// src/app/(dashboard)/pos/new-order/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useCartStore } from '@/lib/store/cartStore'
import ProductGrid from '@/components/pos/ProductGrid'
import Cart from '@/components/pos/Cart'
import PaymentModal from '@/components/pos/PaymentModal'
import { ShoppingCart } from 'lucide-react'
import toast from 'react-hot-toast'

const CATEGORIES = [
  { name: 'All', slug: 'all' },
  { name: 'Espresso', slug: 'espresso' },
  { name: 'Non-Coffee', slug: 'non-coffee' },
  { name: 'Frappe', slug: 'frappe' },
  { name: 'Refreshers', slug: 'refreshers' },
  { name: 'Beverages', slug: 'beverages' },
  { name: 'Pizza', slug: 'pizza' },
]

export default function NewOrderPage() {
  const [products, setProducts] = useState<any[]>([])
  const [selectedCategory, setSelectedCategory] = useState('all')
  const [showPayment, setShowPayment] = useState(false)
  const [loading, setLoading] = useState(true)
  const [isMounted, setIsMounted] = useState(false)
  const supabase = createClient()
  
  // Get cart store values
  const items = useCartStore((state) => state.items)
  const addItem = useCartStore((state) => state.addItem)
  const clearCart = useCartStore((state) => state.clearCart)
  const getSubtotal = useCartStore((state) => state.getSubtotal)
  const getItemCount = useCartStore((state) => state.getItemCount)

  useEffect(() => {
    setIsMounted(true)
    fetchProducts()
  }, [])

  // In src/app/(dashboard)/pos/new-order/page.tsx
// Update the fetchProducts function:

const fetchProducts = async () => {
  try {
    const { data, error } = await supabase
      .from('products')
      .select(`
        *,
        category:categories(name, slug),
        variants:product_variants(*),
        addons:product_addons(*)
      `)
      .eq('is_active', true)
      .eq('is_available', true)
      .order('sort_order')

    if (error) throw error
    
    // Filter variants and addons to only show active ones
    const filteredData = (data || []).map(product => ({
      ...product,
      variants: (product.variants || []).filter((v: any) => v.is_active !== false),
      addons: (product.addons || []).filter((a: any) => a.is_active !== false),
    }))
    
    setProducts(filteredData)
  } catch (error) {
    console.error('Error fetching products:', error)
    toast.error('Failed to load products')
  } finally {
    setLoading(false)
  }
}

  const handleAddToCart = (product: any, variant: any, selectedAddons: any[]) => {
    addItem({
      productId: product.id,
      productName: product.name,
      variantId: variant.id,
      variantName: variant.name,
      price: variant.price,
      quantity: 1,
      addons: selectedAddons || [],
    })
    toast.success(`${product.name} added to cart`)
  }

  const handleCompleteOrder = async (paymentDetails: {
  paymentMethod: string
  processedBy: string
  customerName?: string
  printReceipt: boolean
}) => {
  try {
    const { data: { user } } = await supabase.auth.getUser()
    
    const { data: order, error } = await supabase
      .from('orders')
      .insert({
        staff_id: user?.id,
        processed_by: paymentDetails.processedBy,
        customer_name: paymentDetails.customerName || null,
        payment_method: paymentDetails.paymentMethod,
        subtotal: getSubtotal(),
        total: getSubtotal(),
        status: 'completed'
        // order_number is auto-generated by DB
      })
      .select()
      .single()

    if (error) throw error

      // Insert order items
      const orderItems = items.map(item => ({
        order_id: order.id,
        product_id: item.productId,
        variant_id: item.variantId || null,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity,
        notes: item.notes || null,
      }))

      const { data: insertedItems, error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems)
        .select()

      if (itemsError) throw itemsError

      // Insert addons for each order item
      if (insertedItems) {
        const addonInserts: any[] = []
        insertedItems.forEach((insertedItem: any, index: number) => {
          const cartItem = items[index]
          if (cartItem && cartItem.addons && cartItem.addons.length > 0) {
            cartItem.addons.forEach((addon: any) => {
              addonInserts.push({
                order_item_id: insertedItem.id,
                addon_id: addon.id,
                name: addon.name,
                price: addon.price,
              })
            })
          }
        })

        if (addonInserts.length > 0) {
          await supabase.from('order_item_addons').insert(addonInserts)
        }
      }

      // Print receipt
      if (paymentDetails.printReceipt) {
        const receiptContent = generateReceipt(order, items)
        const receiptWindow = window.open('', '_blank', 'width=300,height=600')
        if (receiptWindow) {
          receiptWindow.document.write(receiptContent)
          receiptWindow.document.close()
          setTimeout(() => receiptWindow.print(), 500)
        }
      }

      toast.success('Order completed successfully!')
      clearCart()
      setShowPayment(false)
      
    } catch (error: any) {
      console.error('Error completing order:', error)
      toast.error('Failed to complete order: ' + error.message)
    }
  }

  const generateReceipt = (order: any, items: any[]) => {
    const date = new Date().toLocaleString('en-PH', { timeZone: 'Asia/Manila' })
    return `
      <html>
        <head>
          <title>Receipt - #${order.order_number}</title>
          <style>
            body { font-family: 'Courier New', monospace; font-size: 11px; width: 280px; margin: 0 auto; padding: 15px; }
            .header { text-align: center; margin-bottom: 15px; }
            .header h2 { margin: 0; font-size: 16px; }
            .divider { border-top: 1px dashed #000; margin: 8px 0; }
            .item { display: flex; justify-content: space-between; margin: 3px 0; }
            .addon { font-size: 10px; padding-left: 10px; color: #666; }
            .total { font-weight: bold; font-size: 14px; margin-top: 8px; }
            @media print { body { width: 80mm; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>AYA Studios</h2>
            <p style="margin:3px 0;">coffee & prints</p>
            <p style="margin:3px 0;">Order #${order.order_number}</p>
            <p style="margin:3px 0; font-size: 10px;">${date}</p>
          </div>
          <div class="divider"></div>
          ${items.map(item => `
            <div class="item">
              <span>${item.quantity}x ${item.productName}</span>
              <span>₱${(item.price * item.quantity).toFixed(2)}</span>
            </div>
            ${item.variantName ? `<div style="font-size:10px;padding-left:10px;color:#666;">${item.variantName}</div>` : ''}
            ${item.addons?.map((a: any) => `
              <div class="addon">+ ${a.name} (₱${a.price.toFixed(2)})</div>
            `).join('') || ''}
          `).join('')}
          <div class="divider"></div>
          <div class="item total">
            <span>TOTAL</span>
            <span>₱${order.total.toFixed(2)}</span>
          </div>
          <div class="divider"></div>
          <p style="text-align:center; margin-top:15px; font-size:10px;">Thank you! ☕</p>
        </body>
      </html>
    `
  }

  // Don't render cart count until mounted to prevent hydration mismatch
  const itemCount = isMounted ? getItemCount() : 0
  const subtotal = isMounted ? getSubtotal() : 0

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-12rem)]">
      {/* Products Section */}
      <div className="flex-1 overflow-hidden flex flex-col">
        <div className="flex gap-2 mb-6 overflow-x-auto pb-2">
          {CATEGORIES.map((cat) => (
            <button
              key={cat.slug}
              onClick={() => setSelectedCategory(cat.slug)}
              className={`px-4 py-2 rounded-xl text-sm font-medium whitespace-nowrap transition-all duration-200 ${
                selectedCategory === cat.slug
                  ? 'bg-brand-primary text-white shadow-soft'
                  : 'bg-white text-brand-text-secondary hover:bg-brand-surface-hover border border-brand-border'
              }`}
            >
              {cat.name}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="flex items-center justify-center h-64">
              <div className="text-center">
                <div className="w-12 h-12 border-4 border-brand-primary/20 border-t-brand-primary rounded-full animate-spin mx-auto mb-4" />
                <p className="text-brand-text-secondary">Loading products...</p>
              </div>
            </div>
          ) : (
            <ProductGrid
              products={products}
              onAddToCart={handleAddToCart}
              selectedCategory={selectedCategory === 'all' ? null : selectedCategory}
            />
          )}
        </div>
      </div>

      {/* Cart Section */}
      <div className="lg:w-96 flex flex-col">
        <div className="card flex-1 flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-brand-text">Current Order</h3>
            {isMounted && (
              <span className="badge bg-brand-primary/10 text-brand-primary">
                {itemCount} items
              </span>
            )}
          </div>

          <div className="flex-1 overflow-y-auto">
            <Cart />
          </div>

          <div className="border-t border-brand-border pt-4 mt-4">
            <div className="flex justify-between items-center mb-4">
              <span className="text-brand-text-secondary">Subtotal</span>
              <span className="text-xl font-bold text-brand-text">
                ₱{subtotal.toFixed(2)}
              </span>
            </div>

            <div className="space-y-2">
              <button
                onClick={() => setShowPayment(true)}
                disabled={items.length === 0}
                className="btn-primary w-full flex items-center justify-center gap-2"
              >
                <ShoppingCart className="w-5 h-5" />
                Proceed to Payment
              </button>
              <button
                onClick={clearCart}
                disabled={items.length === 0}
                className="btn-ghost w-full text-red-500 hover:text-red-600 hover:bg-red-50"
              >
                Clear Cart
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Payment Modal */}
      {showPayment && (
        <PaymentModal
          onClose={() => setShowPayment(false)}
          onComplete={handleCompleteOrder}
          total={subtotal}
        />
      )}
    </div>
  )
}